### ISSUE TITLE
./ocl... not finding device issue...

### ISSUE THREAD

**Issue by trextrader** [10gic/vanitygen-plusplus#11]
When executing from Ubuntu terminal:

Prefix difficulty:             16777216 1111
Difficulty: 16777216
**Could not open any device**
Available OpenCL platforms:
0: [The pocl project] Portable Computing Language
  0: [GenuineIntel] pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, endian little: true
1: [Advanced Micro Devices, Inc.] AMD Accelerated Parallel Processing
  0: [Advanced Micro Devices, Inc.] Hawaii, endian little: true
  1: [Advanced Micro Devices, Inc.] Hawaii, endian little: true

I set the platform -p arg to 1, and same error, to 0 and same error....

./vanitygen++  is working no errors.

Obviously I would like to take advantage of my GPU's.  Currently installed are the amdgpu-pro drivers with opencl=legacy and headless.  It compiled with no errors and built the binaries.
hashcat -I works with the GPU's using opencl, and the output of hashcat -I is as follows:

OpenCL Info:

Platform ID #1
  Vendor  : Advanced Micro Devices, Inc.
  Name    : AMD Accelerated Parallel Processing
  Version : OpenCL 2.1 AMD-APP (3188.4)

  Device ID #1
    Type           : GPU
    Vendor ID      : 1
    Vendor         : Advanced Micro Devices, Inc.
    Name           : Hawaii
    Version        : OpenCL 1.2 AMD-APP (3188.4)
    Processor(s)   : 44
    Clock          : 1000
    Memory         : 2305/2920 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 3188.4

  Device ID #2
    Type           : GPU
    Vendor ID      : 1
    Vendor         : Advanced Micro Devices, Inc.
    Name           : Hawaii
    Version        : OpenCL 1.2 AMD-APP (3188.4)
    Processor(s)   : 44
    Clock          : 1000
    Memory         : 3251/4075 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 3188.4

Platform ID #2
  Vendor  : The pocl project
  Name    : Portable Computing Language
  Version : OpenCL 1.2 pocl 1.4, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG

  Device ID #3
    Type           : CPU
    Vendor ID      : 128
    Vendor         : GenuineIntel
    Name           : pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Version        : OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-skylake
    Processor(s)   : 8
    Clock          : 4200
    Memory         : 4096/13898 MB allocatable
    OpenCL Version : OpenCL C 1.2 pocl
    Driver Version : 1.4

So, clearly its not an opencl issue on my side, so it must be something I need to config in the Makefile perhaps?

Any help with this issue is greatly appreciated. 

/Zap

**Comment by 10gic** [comment]
Try to set device by -d, see what happens. For example `./oclvanitygen++ -p 1 -d 1 1Love`

**Comment by 10gic** [comment]
If you still have this issue after specify platform (-p) and device (-d), please reopen it.
