### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by dextronomous** [10gic/vanitygen-plusplus#12]
getting this message, could not get it to work with gpu, ubuntu or windows,
very nice if this would have started. maybe you could help out a bit, working compiled without errors please, maybe

the generated private key is zero, regenerate it

thanks in advance man,

**Comment by 10gic** [comment]
This is only a debug message. What are the command line parameters used when you start the program? What kind of result do you expect?

**Comment by dextronomous** [comment]
hi ubuntu its this one 

./oclvanitygen++.exe -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20)) 1HsMJxNiV7TLxmoF6u9384382540
this comes Difficulty: 37625930797770282462
then 
$
but ./vanitygen++.exe -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20)) 1HsMJxNiV7TLxmoF6u9384382540Difficulty: 376259307977702824629384382540
Pattern: 1HsMJxNiV7TLxmoF6u
Address: 1HsMJxNiV7TLxmoF6uJNkydxPFDog4NQum
Privkey: KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rHfuE2Tg4nJW

and the error code in windows cmd 
./vanitygen++.exe -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20)) 1HsMJxNiV7TLxmoF6u
the generated private key is zero, regenerate it

**Comment by dextronomous** [comment]
with wich version of visual studio i can build the exe. the precompiled exe's gave same issue. i compiled it trough developer command prompt 2019vs wich just gave the exe files to me, but i guess they are built debug by default or you know how to built the release trough dev.cmd.prompt

**Comment by 10gic** [comment]
`$((256-20))` is a shell arithmetic operation syntax, it may be not supported by windows. Please just use 236 instead of `$((256-20))` in windows.

**Comment by dextronomous** [comment]
no sorry mate 236, 256, not working, just poof after using
then the command prompt, endian little: true
Using OpenCL prefix matcher

**Comment by dextronomous** [comment]
"oclvanitygen++.exe" -p0 -D0:0 -v -k 1LHDHHD
Prefix difficulty:          15058417127 1LHDHHD
Difficulty: 15058417127
Device: NVIDIA GeForce GTX 1660 Ti
Vendor: NVIDIA Corporation (10de)
Driver: 466.11
Profile: FULL_PROFILE
Version: OpenCL 3.0 CUDA
Max compute units: 24
Max workgroup size: 1024
Global memory: 6442450944
Max allocation: 1610612736
OpenCL compiler flags: -DPRAGMA_UNROLL -cl-nv-verbose
Compiling kernel, can take minutes...done!
Build log:

Grid size: 3072x4096
Modular inverse: 24576 threads, 512 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
  0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
1: [Microsoft] OpenCLOn12
  0: [Microsoft] NVIDIA GeForce GTX 1660 Ti, endian little: true
  1: [Microsoft] Microsoft Basic Render Driver, endian little: true
Using OpenCL prefix matcher

g:\

"oclvanitygen++.exe" -p 0 -D 0:0 -v -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20)) 1LLHJH
Prefix difficulty:            259627881 1LLHJH
Difficulty: 259627881
Device: NVIDIA GeForce GTX 1660 Ti
Vendor: NVIDIA Corporation (10de)
Driver: 466.11
Profile: FULL_PROFILE
Version: OpenCL 3.0 CUDA
Max compute units: 24
Max workgroup size: 1024
Global memory: 6442450944
Max allocation: 1610612736
OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
Loading kernel binary f9f0522d5719c0452a7cbbf577f92e98.oclbin
Grid size: 3072x4096
Modular inverse: 24576 threads, 512 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
  0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
1: [Microsoft] OpenCLOn12
  0: [Microsoft] NVIDIA GeForce GTX 1660 Ti, endian little: true
  1: [Microsoft] Microsoft Basic Render Driver, endian little: true
Using OpenCL prefix matcher
the generated private key is zero, regenerate it

**Comment by 10gic** [comment]
@dextronomous  Many people report oclvanitygen++.exe can't be launched in windows. It seems you launch oclvanitygen++.exe successfully.

Could you run following simpler command line (remove option -Z and -l):
`oclvanitygen++.exe -p 0 -D 0:0 -v -F compressed 1111`

After finished, please share a screenshot of your terminal.

**Comment by 10gic** [comment]
Another question: Do you see message 'the generated private key is zero, regenerate it' **repeatedly** in terminal? Please share a screenshot of when you run into this error.

**Comment by dextronomous** [comment]
the thing is even after the build, i still have to use you'r prebuilt dll files, then it starts, otherwise it says no *.dll
three dll's needed out of 4 to make it start, it does not seem to need the mscv100.dll file. building inside ubuntu fine, with gpu, used the default files, inside your program, i have no linux working with gpu on my win10, ubuntu20.04, headache fixing the cuda stuff, windows insider latest version btw, latest nvidia drivers 466. something, got a 1660ti, now. it works all over the place, besides here. vanitygen++ gave as you can see good results. 

vanitygen++.exe -F compressed -Z 000000000000000000000000000000000000000000000000E000000A00000000 -l $((256-64)) 16jY7qLJnxb7CH
Difficulty: 33248746606520501101169
[479.28 Kkey/s][total 1964288][Prob 0.0%][50% in 1.524784e+09y]

oclvanitygen++.exe -p 0 -D 0:0 -v -F compressed 1111
Prefix difficulty:             16777216 1111
Difficulty: 16777216
Device: NVIDIA GeForce GTX 1660 Ti
Vendor: NVIDIA Corporation (10de)
Driver: 466.11
Profile: FULL_PROFILE
Version: OpenCL 3.0 CUDA
Max compute units: 24
Max workgroup size: 1024
Global memory: -2147483648
Max allocation: 1610612736
OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
Loading kernel binary f9f0522d5719c0452a7cbbf577f92e98.oclbin
Grid size: 3072x4096
Modular inverse: 24576 threads, 512 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
  0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
1: [Microsoft] OpenCLOn12
  0: [Microsoft] NVIDIA GeForce GTX 1660 Ti, endian little: true
  1: [Microsoft] Microsoft Basic Render Driver, endian little: true
Using OpenCL prefix matcher

G:\vanitygen-plusplus-0.1.0>powershell Get-Date

**Comment by 10gic** [comment]
It's very strange. **I don't see any error in following output**. 
```
oclvanitygen++.exe -p 0 -D 0:0 -v -F compressed 1111
Prefix difficulty: 16777216 1111
Difficulty: 16777216
Device: NVIDIA GeForce GTX 1660 Ti
Vendor: NVIDIA Corporation (10de)
Driver: 466.11
Profile: FULL_PROFILE
Version: OpenCL 3.0 CUDA
Max compute units: 24
Max workgroup size: 1024
Global memory: -2147483648
Max allocation: 1610612736
OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
Loading kernel binary f9f0522d5719c0452a7cbbf577f92e98.oclbin
Grid size: 3072x4096
Modular inverse: 24576 threads, 512 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
1: [Microsoft] OpenCLOn12
0: [Microsoft] NVIDIA GeForce GTX 1660 Ti, endian little: true
1: [Microsoft] Microsoft Basic Render Driver, endian little: true
Using OpenCL prefix matcher
```

**After output line `Using OpenCL prefix matcher`, does the program exit normally or crash?**

I run same command in CentOS, here is the output:
```
# ./oclvanitygen++ -p 0 -D 0:0 -v -F compressed 1111
Prefix difficulty:             16777216 1111
Difficulty: 16777216
Device: Tesla T4
Vendor: NVIDIA Corporation (10de)
Driver: 440.95.01
Profile: FULL_PROFILE
Version: OpenCL 1.2 CUDA
Max compute units: 40
Max workgroup size: 1024
Global memory: 15843721216
Max allocation: 3960930304
OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
Loading kernel binary 3ebb018803fd84e2b3e5a21ce3ad6186.oclbin
Grid size: 2560x4096
Modular inverse: 40960 threads, 256 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
  0: [NVIDIA Corporation] Tesla T4, endian little: true
Using OpenCL prefix matcher
Pattern: 1111
Pubkey (hex): 041f0773d82cff414557dbe9cdb76e275878916cb220aaaaca39c801ad47091c0c294fd3006818b0d5e93053dea16b0f340db407e760568f78365048d4731c04e2
Privkey (hex): 6FAC1ED61BE7082BEDB04976CA6C07627F845A205BF19ADEB61A1301A4D71CED
Privkey (ASN1): 3082011302010104206fac1ed61be7082bedb04976ca6c07627f845a205bf19adeb61a1301a4d71ceda081a53081a2020101302c06072a8648ce3d0101022100fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f300604010004010704410479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8022100fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141020101a144034200041f0773d82cff414557dbe9cdb76e275878916cb220aaaaca39c801ad47091c0c294fd3006818b0d5e93053dea16b0f340db407e760568f78365048d4731c04e2
Address: 1111GBgrsAvVPkqaZQs5Gdq1ormRAWGQv
Privkey: KzxncprGpzaLVsCn2AZZfdwFsT8ETc6pggNKAhtTcHBSwgePcBKX
Halting...done!
```

After output `Using OpenCL prefix matcher`, following 7 lines are outputted:
```
Pattern: 1111
Pubkey (hex): 041f0773d82cff414557dbe9cdb76e275878916cb220aaaaca39c801ad47091c0c294fd3006818b0d5e93053dea16b0f340db407e760568f78365048d4731c04e2
Privkey (hex): 6FAC1ED61BE7082BEDB04976CA6C07627F845A205BF19ADEB61A1301A4D71CED
Privkey (ASN1): 3082011302010104206fac1ed61be7082bedb04976ca6c07627f845a205bf19adeb61a1301a4d71ceda081a53081a2020101302c06072a8648ce3d0101022100fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f300604010004010704410479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8022100fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141020101a144034200041f0773d82cff414557dbe9cdb76e275878916cb220aaaaca39c801ad47091c0c294fd3006818b0d5e93053dea16b0f340db407e760568f78365048d4731c04e2
Address: 1111GBgrsAvVPkqaZQs5Gdq1ormRAWGQv
Privkey: KzxncprGpzaLVsCn2AZZfdwFsT8ETc6pggNKAhtTcHBSwgePcBKX
Halting...done!
```

**Comment by dextronomous** [comment]
i tried to build with cuda 8,9,10,11, so wich cuda should i use should not matter,
"oclvanitygen++.exe" -p 0 -D 0:0 -v -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20)) 1LLHJH
Prefix difficulty:            259627881 1LLHJH
Difficulty: 259627881
Device: NVIDIA GeForce GTX 1660 Ti
Vendor: NVIDIA Corporation (10de)
Driver: 466.11
Profile: FULL_PROFILE
Version: OpenCL 3.0 CUDA
Max compute units: 24
Max workgroup size: 1024
Global memory: 6442450944
Max allocation: 1610612736
OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
Loading kernel binary f9f0522d5719c0452a7cbbf577f92e98.oclbin
Grid size: 3072x4096
Modular inverse: 24576 threads, 512 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
  0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
1: [Microsoft] OpenCLOn12
  0: [Microsoft] NVIDIA GeForce GTX 1660 Ti, endian little: true
  1: [Microsoft] Microsoft Basic Render Driver, endian little: true
Using OpenCL prefix matcher
the generated private key is zero, regenerate it
the generated private key is zero, regenerate it

**Comment by 10gic** [comment]
> i tried to build with cuda 8,9,10,11, so wich cuda should i use should not matter,
> "oclvanitygen++.exe" -p 0 -D 0:0 -v -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20)) 1LLHJH
> Prefix difficulty: 259627881 1LLHJH
> Difficulty: 259627881
> Device: NVIDIA GeForce GTX 1660 Ti
> Vendor: NVIDIA Corporation (10de)
> Driver: 466.11
> Profile: FULL_PROFILE
> Version: OpenCL 3.0 CUDA
> Max compute units: 24
> Max workgroup size: 1024
> Global memory: 6442450944
> Max allocation: 1610612736
> OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
> Loading kernel binary f9f0522d5719c0452a7cbbf577f92e98.oclbin
> Grid size: 3072x4096
> Modular inverse: 24576 threads, 512 ops each
> Available OpenCL platforms:
> 0: [NVIDIA Corporation] NVIDIA CUDA
> 0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
> 1: [Microsoft] OpenCLOn12
> 0: [Microsoft] NVIDIA GeForce GTX 1660 Ti, endian little: true
> 1: [Microsoft] Microsoft Basic Render Driver, endian little: true
> Using OpenCL prefix matcher
> the generated private key is zero, regenerate it
> the generated private key is zero, regenerate it
> endless faaaast loop zero, regenerate it

Remove "-Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20))", and just run `oclvanitygen++.exe" -p 0 -D 0:0 -v -F compressed 1LLHJH` directly, see what error happens?

**Comment by 10gic** [comment]
```
Replace
-Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-20))
To
-Z 00000000000000000000000000000000000000000000000000000000000
```

Run `oclvanitygen++.exe" -p 0 -D 0:0 -v -F compressed -Z 00000000000000000000000000000000000000000000000000000000000 1LLHJH` , see what error happens.

**Comment by dextronomous** [comment]
oclvanitygen++.exe -p 0 -D 0:0 -v -F compressed -Z 00000000000000000000000000000000000000000000000000000000000 1LLHJH - Assertion failed: strlen(optarg) % 2 == 0, file oclvanitygen.c, line 367 - C:\prebuilt.win32.v0.1.0>pause - Press any key to continue . . . 
oclvanitygen++.exe -p 0 -D 0:0 -v -F compressed -Z 00000000000000000000000000000000000000000000000000000000000 1LLHJH - Assertion failed: strlen(optarg) % 2 == 0, file oclvanitygen.c, line 367 - C:\vanitygen-plusplus-master>pause - Press any key to continue . . .

oclvanitygen++.exe -p 0 -D 0:0 -v -F compressed 1LLHJH
Prefix difficulty:            259627881 1LLHJH
Difficulty: 259627881
Device: NVIDIA GeForce GTX 1660 Ti
Vendor: NVIDIA Corporation (10de)
Driver: 470.14
Profile: FULL_PROFILE
Version: OpenCL 3.0 CUDA
Max compute units: 24
Max workgroup size: 1024
Global memory: 6442450944
Max allocation: 1610612736
OpenCL compiler flags: -DPRAGMA_UNROLL -DCOMPRESSED_ADDRESS -cl-nv-verbose
Compiling kernel, can take minutes...done!
Build log:
ptxas info    : 0 bytes gmem, 968 bytes cmem[3]
ptxas info    : Compiling entry function 'hash_ec_point_search_prefix' for 'sm_75'
ptxas info    : Function properties for hash_ec_point_search_prefix
ptxas         .     96 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 372 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function 'hash_ec_point_get' for 'sm_75'
ptxas info    : Function properties for hash_ec_point_get
ptxas         .     64 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 80 registers, 364 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function 'heap_invert' for 'sm_75'
ptxas info    : Function properties for heap_invert
ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 360 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function 'ec_add_grid' for 'sm_75'
ptxas info    : Function properties for ec_add_grid
ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 92 registers, 368 bytes cmem[0], 8 bytes cmem[2]
Grid size: 3072x4096
Modular inverse: 24576 threads, 512 ops each
Available OpenCL platforms:
0: [NVIDIA Corporation] NVIDIA CUDA
  0: [NVIDIA Corporation] NVIDIA GeForce GTX 1660 Ti, endian little: true
Using OpenCL prefix matcher

C:\vanitygen-plusplus-master>pause
Press any key to continue . . .

**Comment by dextronomous** [comment]
it is working with your latest updated code, the nmake and the exe working as right as we speak, with the -Z -l
oclvanitygen++.exe -D0:0,grid=1024x1024 -v -k -F compressed -Z 0000000000000000000000000000000000000000000000000000000000 111111

one thing man , you really made my time on it worth, thank you so much, really happy with a dev like you. thanks again brother.
