### ISSUE TITLE
Hanging after "Prefix ... too long, lets try it anyways!" ?

### ISSUE THREAD

**Issue by godzillakong** [10gic/vanitygen-plusplus#16]
Command oclvanitygen++.exe  -v 1ABCDEFGHJKLMNPQRSTUVWXYZabcdefghj generated a message:
 "Prefix '1ABCDEFGHJKLMNPQRSTUVWXYZabcdefghj' is too long, lets try it anyways!"
 It seems to hang after that. Had to ctrl-c to get out of it.

**Comment by 10gic** [comment]
Currently, it is not possible to resolve such a long prefix.
