### ISSUE TITLE
Trouble building in Win32

### ISSUE THREAD

**Issue by nbwolfpack** [10gic/vanitygen-plusplus#20]
When i try to build to build the program in Win32, I get this error:

vanitygen.c(66): error C2057: expected constant expression
vanitygen.c(66): error c2466: cannot allocate an array of constant size 0
vanitygen.c(66): error c2133: 'ppnt': unknown size

The code is from:

vg_thread_loop(void *arg)
{
	unsigned char hash_buf[128];
	unsigned char *eckey_buf;
	unsigned char hash1[32];

	int i, c, len, output_interval;
	int hash_len;

	const BN_ULONG rekey_max = 10000000;
	BN_ULONG npoints, rekey_at, nbatch;

	vg_context_t *vcp = (vg_context_t *) arg;
	EC_KEY *pkey = NULL;
	const EC_GROUP *pgroup;
	const EC_POINT *pgen;
	const int ptarraysize = 256;
	EC_POINT *ppnt[ptarraysize];

How do I fix the errors when I downloaded the file and didn't change anything in the code?

**Comment by 10gic** [comment]
Suggest you look at this https://github.com/10gic/vanitygen-plusplus/issues/26#issuecomment-1123393684
