### ISSUE TITLE
oclvanitygen++ not works in Windows10

### ISSUE THREAD

**Issue by AngelTs** [10gic/vanitygen-plusplus#26]
When run prebuilt.win32.v0.1.0.exe, only shows the difficult and stops

**Comment by 10gic** [comment]
Could you provide more error info like screenshots?
By the way, does the tool `vanitygen++` work under Windows 10?

**Comment by AngelTs** [comment]
> Could you provide more error info like screenshots? By the way, does the tool `vanitygen++` work under Windows 10?
Sorry for delay- vanitygen works OK, but oclvanitygen produce noting!

C:\$ABC$\xxx>oclvanitygen++ -C ETH 0x9999
Generating ETH Address
Difficulty: 65536

C:\$ABC$\xxx>oclvanitygen++ -C ETH 0x99
Generating ETH Address
Difficulty: 256

C:\$ABC$\xxx>oclvanitygen++ -C BTC 1aaa
Generating BTC Address
Difficulty: 4553521

C:\$ABC$\xxx>oclvanitygen++ -C BTC 1aa
Generating BTC Address
Difficulty: 78508

C:\$ABC$\xxx>vanitygen++ -C BTC 1aa
Generating BTC Address
Difficulty: 78508
BTC Pattern: 1aa
BTC Address: 1aaJuP6PzsJvaMCuoRGJdoSMbRcV3Y5Fs
BTC Privkey: 5KfdocQCJh8v8ncLSEp55AyyKdkQQL3bmC8iSMbEL1TYE9fz2Lw

C:\$ABC$\xxx>vanitygen++ -C BTC 1aaa
Generating BTC Address
Difficulty: 4553521
BTC Pattern: 1aaa
BTC Address: 1aaaGHNfCDcCoMbXasQXbi9D9rVNhdCFG
BTC Privkey: 5JRy6JqUxfGp14pnk52wWvf4z4tKDZD63xRH3parcmHxhqV5Dm4

C:\$ABC$\xxx>vanitygen++ -C ETH 0x99
Generating ETH Address
Difficulty: 256
ETH Pattern: 0x99
ETH Address: 0x99273dA91C80eE97D2d2a53A5F7699bDdc0500A8
ETH Privkey: 0xa05f397b0287e35917c3240300655f580f3c798d3956f7bcece0730945cd9b28

C:\$ABC$\xxx>vanitygen++ -C ETH 0x9999
Generating ETH Address
Difficulty: 65536
ETH Pattern: 0x9999
ETH Address: 0x999971605c443F2E220621d8Ea39EFcC0d6d9cE2
ETH Privkey: 0x75cfc21fa1f607bfd0344adcf5688e7c18f995d3806de4e6b03f9370b22e4cdb

C:\$ABC$\xxx>

**Comment by 5k1n** [comment]
Yes, same problem. OCL just show difficult and stop
non ocl works well...

**Comment by 5k1n** [comment]
C:\Users\Andrew\Desktop\vanitygen\++>oclvanitygen++ -C BTC 1aa
Generating BTC Address
Difficulty: 78508

C:\Users\Andrew\Desktop\vanitygen\++>vanitygen++ -C ETH 0x9999
Generating ETH Address
Difficulty: 65536
ETH Pattern: 0x9999
ETH Address: 0x9999cAc8eECA785F617153092388F5044C25798F
ETH Privkey: 0x8732720003388d64bfc5e82161339fe5839f5aebecf32d9ebe3cacb9336506d4

**Comment by 5k1n** [comment]
> Could you provide more error info like screenshots? By the way, does the tool `vanitygen++` work under Windows 10?

look

**Comment by AngelTs** [comment]
One possible solution: Vanitygen plus plus for VS2019, https://github.com/AngelTs/vanitygen-plusplus-ported-for-VS2019

**Comment by Kofro** [comment]
> One possible solution: Vanitygen plus plus ported for VS2019, https://github.com/AngelTs/vanitygen-plusplus-ported-for-VS2019

Worked for me

**Comment by anshukrsingh** [comment]
> > One possible solution: Vanitygen plus plus ported for VS2019, https://github.com/AngelTs/vanitygen-plusplus-ported-for-VS2019
> 
> Worked for me

Can you please provide details , what you do after cloning the repo. , how you build?, command to make it run properly?

**Comment by 10gic** [comment]
There is a new release, see https://github.com/10gic/vanitygen-plusplus/releases/tag/v0.2.0

**Comment by LuizClaudioDiniz** [comment]
work with win11
