### ISSUE TITLE
Random or sequential in solving puzzle

### ISSUE THREAD

**Issue by AsicPrince** [10gic/vanitygen-plusplus#36]
Let's say I'm solving puzzle 64 and I will stop program after few hours then when i restart, will your program start at new/random point or it's same point every time?
If it's only start at 1point then how can we do random?

**Comment by 10gic** [comment]
It starts at random point, see:
https://github.com/10gic/vanitygen-plusplus/blob/1b86968e1cfbaea9bb24ab1d573c057722dec2b9/oclengine.c#L2116

**Comment by AsicPrince** [comment]
can you please modify your code to searching for a list of addresses?
