### ISSUE TITLE
./vanitygen++ -C LTC results to XLM address generation

### ISSUE THREAD

**Issue by LordSkele** [10gic/vanitygen-plusplus#4]
./vanitygen++ -C LTC (whatever)
defaults to XLM address?

in vanitygen.c it defaults to BTC address generation, then XLM, then any other crypto.
Removing the XLM else block doesnt help and LTC still results in XLM address generation.

I didnt start messing with things until it kept saying "Generating XLM address" so I dont think I fucked anything up.

**Comment by 10gic** [comment]
@LordSkele This issue has been fixed. Thanks for reporting the issue.

Here is an example:
```
$ ./vanitygen++ -C LTC LLLL
Generating LTC Address
Difficulty: 78508
LTC Pattern: LLLL
LTC Address: LLLL6Ays9TcYYqFmtMUNMcb2Jdie6PFoUH
LTC Privkey: 6vYPuExcggGZyqui3Nd7DxLtiNR3ZMPyYDu9anosngKjA7LggkW
```
