### ISSUE TITLE
Mac mini M1 - 'openssl/sha.h' file not found 

### ISSUE THREAD

**Issue by bane77111** [10gic/vanitygen-plusplus#40]
Do anyone knows how to resolve the issue for this error, on Mac mini M1:

-Mac-mini vanitygen-plusplus % make
cc -ggdb -O3 -Wall -I/usr/local/opt/openssl/include   -c -o vanitygen.o vanitygen.c
vanitygen.c:26:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^~~~~~~~~~~~~~~

Thanks!

**Comment by 10gic** [comment]
May be you need install openssl. Try run `brew install openssl@1.1` firstly.

**Comment by bane77111** [comment]
i already have it,...

> May be you need install openssl. Try run `brew install openssl@1.1` firstly.

I already have it

**Comment by 10gic** [comment]
Sorry, I don't have a Mac mini M1 on hand. Hope others can help you.

**Comment by bane77111** [comment]
> Sorry, I don't have a Mac mini M1 on hand. Hope others can help you.

np, thanks for trying

**Comment by ceemoneyx** [comment]
I'm getting the same error trying to compile it on a raspberry pi, I keep getting the error "yum: command not found" 

I'm fairly new to this so any help would be appreciated!

**Comment by cbrunnkvist** [comment]
Assuming you have already installed OpenSSL via Homebrew (`brew install openssl`), the easiest way is something like: 

    C_INCLUDE_PATH=/opt/homebrew/opt/openssl/include:/opt/homebrew/include LIBRARY_PATH=/opt/homebrew/opt/openssl/lib make


There might be some `ld: warning: directory not found` warning, but it's just the linker that gets confused. _Ideally_ the `Makefile` should be rewritten for portability, as suggested in [a different issue](https://github.com/10gic/vanitygen-plusplus/issues/32#issuecomment-1140464015), but in a less hardcoded way.

**Comment by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [comment]
> Do anyone knows how to resolve the issue for this error, on Mac mini M1:
> 
> -Mac-mini vanitygen-plusplus % make cc -ggdb -O3 -Wall -I/usr/local/opt/openssl/include -c -o vanitygen.o vanitygen.c vanitygen.c:26:10: fatal error: 'openssl/sha.h' file not found #include <openssl/sha.h> ^~~~~~~~~~~~~~~
> 
> Thanks!

Have you solved your issue? I have troubles to make it on a Mac too!
