### ISSUE TITLE
Issues running on Raspbian

### ISSUE THREAD

**Issue by ceemoneyx** [10gic/vanitygen-plusplus#41]
Is there a way to compile this on Raspbian? I'm having issues despite (i think?) installing the correct prerequisite libraries. I managed to get it compiled on CentOS but am still having issues running the compiled program on my Raspbian OS.

It returns the following error
`"./vanitygen++: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory" 
`

I tried in stalling the library with:
`sudo apt install libpcre3 libpcre3-dev`

but still no luck.
I'm new here so any help would be greatly appreciated!

**Comment by 10gic** [comment]
The version of pcre does not match. Your binary needs version 1, but you installed version 3.
You can try to install a lower version of pcre in the runtime environment, or install a higher version of pcre in the build environment.

**Comment by ceemoneyx** [comment]
Would you have any idea why I'm getting this error when installing PCRE-1? 

`make[2]: Entering directory '/home/cee/pcre-8.45'
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libpcre.la libpcreposix.la libpcrecpp.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libpcre.so.1.2.13 /usr/local/lib/libpcre.so.1.2.13
/usr/bin/install: cannot create regular file '/usr/local/lib/libpcre.so.1.2.13': Permission denied
make[2]: *** [Makefile:1537: install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/cee/pcre-8.45'
make[1]: *** [Makefile:3076: install-am] Error 2
make[1]: Leaving directory '/home/cee/pcre-8.45'
make: *** [Makefile:3069: install] Error 2
`

**Comment by 10gic** [comment]
There is error message: `/usr/bin/install: cannot create regular file '/usr/local/lib/libpcre.so.1.2.13': Permission denied.`
No permission to create file, maybe you need to use sudo to execute your command.

**Comment by ceemoneyx** [comment]
hmm, I ran and same issue
`sudo ./configure && make && make install`

**Comment by ceemoneyx** [comment]
is there perhaps a way to compile it on CentOS so that it's standalone?

**Comment by 10gic** [comment]
> hmm, I ran `sudo ./configure && make && make install`
> 
> and same issue

Try this `./configure && make && sudo make install`.

Ref: https://askubuntu.com/questions/634620/when-using-and-sudo-on-the-first-command-is-the-second-command-run-as-sudo-t

**Comment by ceemoneyx** [comment]
hmmm one step forward two steps back LOL, so that time it didn't give me an error and looks like it ran all the way through the make and install functions, however after a reboot it still doesn't look like any pcre installed.

I'm just getting `bash: pcre: command not found
` when i run `pcre -version`, 

and i still get the `./vanitygen++: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
`when trying to run the compiled vanitygen from the desktop 

Am I missing something else here perhaps?

**Comment by 10gic** [comment]
Try run `export LD_LIBRARY_PATH=/usr/local/lib` before  running the command `./vanitygen++`
If it works, put `export LD_LIBRARY_PATH=/usr/local/lib` into file ~/.bashrc

**Comment by ceemoneyx** [comment]
Soooooo It's saying it's missing libcrypto.so.10 now 🙄 I feel like I'm closer now

`./vanitygen++: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
`

**Comment by ceemoneyx** [comment]
This `export LD_LIBRARY_PATH=/usr/local/lib' didn't work but I figured out compiling it on Raspbian. Thank you!

**Comment by ceemoneyx** [comment]
This worked thank you!!!
