### ISSUE TITLE
 Library not loaded

### ISSUE THREAD

**Issue by bane77111** [10gic/vanitygen-plusplus#42]
Hi again

I have another issue with mac M1. Thing is that i can run the script on my laptop Mac (to slow), but on Mac M1 i get library not loaded:

dyld[15981]: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/lusee/vanitygen-plusplus1/vanitygen++
  Reason: tried: '/usr/local/opt/pcre/lib/libpcre.1.dylib' (no such file), '/usr/local/lib/libpcre.1.dylib' (no such file), '/usr/lib/libpcre.1.dylib' (no such file)

So i guess that /usr/...... /libpcre.1.dylib should be in /local directory but on M1 is at usr/bin/...

Is there way to fix this?

Thanks in advance

**Comment by ceemoneyx** [comment]
Had a similar issue on Linux, I had to install the old PCRE1 library for this to work.

**Comment by bane77111** [comment]
> 

I checked, have an old version on both comp.

**Comment by 10gic** [comment]
Before executing, try to set DYLD_LIBRARY_PATH to the directory of the dynamic library libpcre.1.dylib.
