### ISSUE TITLE
vanitygen for Tron

### ISSUE THREAD

**Issue by Ch3n4y** [10gic/vanitygen-plusplus#44]
this is not an issue actually, but inquiry to add Tron blockchain to vanity gen
https://developers.tron.network/docs/account

**Comment by Ch3n4y** [comment]
https://secretscan.org/PrivateKeyTron

**Comment by chainsbro** [comment]
@10gic 
i second this.  Would be willing to donate for implementation.

**Comment by 10gic** [comment]
@chainsbro Tron is a good project. But, I'm busy with other things and don't have much time for this.

BTW, how much would you want to donate? 🤪

**Comment by 10gic** [comment]
> @10gic i second this. Would be willing to donate for implementation. Is there any other necessary information required for addition?

It seems there are two formats for TRON account addresses: Hex and Base58 (starts with T). Which format is expected to be supported? I think vanity address for Base58 is more meaningful. Am I right?

**Comment by chainsbro** [comment]
> > @10gic i second this. Would be willing to donate for implementation. Is there any other necessary information required for addition?
> 
> It seems there are two formats for TRON account addresses: Hex and Base58 (starts with T). Which format is expected to be supported? I think vanity address for Base58 is more meaningful. Am I right?

Hello,  Yes, the Base58 address beginning with T is what's needed.

For donations, is there somewhere private to chat?

**Comment by 10gic** [comment]
@chainsbro  You can contact me by email at:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/2391796/202958087-a05d348f-b463-4cd7-941c-fc89fdc715ca.png">

**Comment by MoriZalev** [comment]
> > @10gicя підтримую це. Були б готові пожертвувати на реалізацію. Чи потрібна інша необхідна інформація для доповнення?
> 
> Здається, існує два формати для адрес облікових записів TRON: Hex і Base58 (починається з T). Який формат очікується підтримувати? Я думаю, що адреса марнославства для Base58 є більш значущою. Чи правий я?

HI, please give me your contact.
