### ISSUE TITLE
OpenSSL Issue

### ISSUE THREAD

**Issue by ceemoneyx** [10gic/vanitygen-plusplus#47]
Hey I'm having an issue trying to generate Taproot and Cosmos addresses. I've compiled and installed Open SSL 3.0 and when i run `openssl version` It does in fact show that 3.0 is installed, it reads : `Open SSL 3.0.0 17 Sept`

However when I try to generate a Taproot or Cosmos address with Vanitygen it says 
`OpenSSL 3.0 (or higher) required to generate this address`

also when running `dpkg -l openssl` I get:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-fules/Unpacked/half-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/     Name                Version                              Architecture      Description
+++-============-===================-============-===================
ii     openssl		1.1.1n-0+deb11u3+rpt1	armhf		Secure Sockets Layer toolkit….
```

*** Running on Linux on a Raspberry Pi

**Comment by 10gic** [comment]
Do you have two versions of openssl installed?
The output of `dpkg -l openssl` shows that the version 1.1.1n is installed, may be this version of openssl is used when building.

**Comment by ceemoneyx** [comment]
I wouldn’t I have to recompile Vanitygen after installing open SSL would I?

**Comment by 10gic** [comment]
I suggest you use `nix-build` to build it.

**Comment by ceemoneyx** [comment]
Okay I'm not sure what that is but will do some digging haha

**Comment by 10gic** [comment]
1. First install nix-build if it is not installed, for example: `sh <(curl -L https://nixos.org/nix/install)`
2. Then, run `nix-build` in project root.
3. If all succeeded, the generated binary is`./result/bin/vanitygen++`.
