### ISSUE TITLE
speed comparison vs profanity2

### ISSUE THREAD

**Issue by chainsbro** [10gic/vanitygen-plusplus#50]
I have a suspicion that plusplus is not using both gpus whereas profanity2 is. 

 Is there anyway to confirm/deny this?

![vanity-plus-plus-prefix](https://user-images.githubusercontent.com/118589822/202914778-23d659ab-2ceb-41a2-9597-111e3df06c84.png)
![profanity-speed](https://user-images.githubusercontent.com/118589822/202914767-de1d01d3-1206-4c16-b678-88311a7eadd8.png)

**Comment by 10gic** [comment]
Your can use NVIDIA System Management Interface (nvidia-smi) to check the GPU utilization.

**Comment by chainsbro** [comment]
My mistake, had to set the -D switch for multiple gpus

**Comment by 10gic** [comment]
I don't have a computer with multiple GPU devices. Could you show the full command line arguments and the running screenshot? This might help others.

**Comment by chainsbro** [comment]
Sure, simply include a -D switch for every gpu, eg

./oclvanitygen++ -C ETH 1234567890 -D 0:0 -D 0:1 -D 0:2 etc etc

Perhaps there's a better way to do it, but this seemed to work
