### ISSUE TITLE
Implement different LTC address types

### ISSUE THREAD

**Issue by clydesdales** [10gic/vanitygen-plusplus#51]
Similar to bitcoin, it would be useful to select different LTC address types

P2PKH - Legacy. Address starts with a L. (Currently supported)

P2SH - SegWit compatible. Address starts with a M.

Bech32 - SegWit native. Address starts with ltc1.

**Comment by 10gic** [comment]
Now, LTC Bech32 address is supported. However, there is no plan to support LTC SegWit compatible address.
