### ISSUE TITLE
The quiet flag does not suppress any output

### ISSUE THREAD

**Issue by SatoshiGuacamole** [10gic/vanitygen-plusplus#52]
## Expected Behavior

I expect the **Generating BTC Address** line to not show up when the **-q** flag is passed.

`./result/bin/vanitygen++ -C BTC -z -q 1`

```
BTC,1,1FKEp7Y9qwLC7krMg9B6arEoMyXqBuqEtw,5K6Q5Z7q91ujRjfreyRAjt1BZbjyfvqcnBmwRPPkLG3rWf6D9b3
```

## Current Behavior

`./result/bin/vanitygen++ -C BTC -z -q 1`

```
Generating BTC Address
BTC,1,1FKEp7Y9qwLC7krMg9B6arEoMyXqBuqEtw,5K6Q5Z7q91ujRjfreyRAjt1BZbjyfvqcnBmwRPPkLG3rWf6D9b3
```

## Steps to Reproduce

1. Install using nix-build:
```
FROM nixos/nix:2.12.0

RUN git clone https://github.com/10gic/vanitygen-plusplus.git \
    && cd vanitygen-plusplus \
    && git checkout c072eb57c68381c049ff915416bba8d3044f6073 \
    && nix-build
```

2. Execute `./result/bin/vanitygen++ -C BTC -q 1`

## Context (Environment)

I would like to transmit the command output using *socat* so that I can use the results of this excellent program in my web application with minimal post processing required.

**Comment by 10gic** [comment]
The purpose of option `-q` is not to suppress output, but to reduce unnecessary output. You can redirect stdout/stderr if you don't want any output. For example, `/result/bin/vanitygen++ -C BTC 1Love 2>/dev/null 1>/dev/null`
