### ISSUE TITLE
When trying to import TRX Privkey into tronlink,  it says Unrecognized key format

### ISSUE THREAD

**Issue by GG4mida** [10gic/vanitygen-plusplus#59]
```bash
./vanitygen++ -C TRX TH
```
![image](https://user-images.githubusercontent.com/75657291/213660769-7a664ab3-1828-4046-83c3-94935f943c9f.png)

then i attempt import the privkey `5JS5MM9WgHQAWQr6Fj6BJwdVXoomRAcZoE3hcStE2uCQu9CVDfj` into my tronlink:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/75657291/213661138-be031f21-98e2-422e-8db1-d04b203c5bdb.png">

Can you spare some time to solve this problem? donate if needed.

**Comment by 10gic** [comment]
I'm going to look into this issue. Donations are welcome, the amount is up to you.

**Comment by 10gic** [comment]
This issue is fixed. If you find that there are still problems, please reopen issue.

**Comment by Bitcoin228** [comment]
When trying to import TRX Privkey into tronlink, it says Unrecognized key format
