### ISSUE TITLE
When trying to import TRX Privkey into tronlink, it says Unrecognized key format

### ISSUE THREAD

**Issue by Bitcoin228** [10gic/vanitygen-plusplus#60]
When trying to import TRX Privkey into tronlink, it says Unrecognized key format
the same after the update. private key error

**Comment by cainia0** [comment]
see #59
https://github.com/10gic/vanitygen-plusplus/issues/59

**Comment by Bitcoin228** [comment]
> см. [#59 ](https://github.com/10gic/vanitygen-plusplus/issues/59) #59

После этого обновления снова неверный формат приватных ключей...

**Comment by 10gic** [comment]
@Bitcoin228 I can't reproduce this issue, could you share the detailed steps? Screenshots would be best.

**Comment by 10gic** [comment]
If you run into problems, please reopen this issue.
