### ISSUE TITLE
CONTACT 

### ISSUE THREAD

**Issue by MoriZalev** [10gic/vanitygen-plusplus#62]
Hello, how can I contact you? I am willing to pay you for your work.

**Comment by NHGIT61** [comment]
Maybe you can donate directly to his address
BTC: 123456WcsbL1NRiU2H3jNSSDEp3q8M9u8t
ETH: 0x123456E35147E215FBec2A1B4502C7Cf6Ecb62cD
These addresses are written at the bottom of the project

**Comment by qptrello** [comment]
Is it possible to increase the GPU, I hope to have some TRX address last is 8888，Now only the CPU -r parameter can be used

**Comment by 10gic** [comment]
<img width="315" alt="github" src="https://user-images.githubusercontent.com/2391796/217897730-bbc77ee5-1af6-49a3-9f8b-9830f8352f8b.png">

@MoriZalev You can copy the email from my public profile: https://github.com/10gic
