### ISSUE TITLE
Issues Compiling

### ISSUE THREAD

**Issue by ceemoneyx** [10gic/vanitygen-plusplus#73]
I'm having issues compiling on Raspbian OS, when running 'make' I get the following output:
I've run both 'make' and 'sudo make' and installed all the dependencies

Thanks in advance for the help!

`cc vanitygen.o pattern.o util.o groestl.o sha3.o ed25519.o stellar.o base32.o crc16.o simplevanitygen.o bech32.o segwit_addr.o -o vanitygen++ -ggdb -O3 -Wall -Wno-deprecated -lpcre -lcrypto -lm -lpthread
/usr/bin/ld: util.o: in function `vg_protect_crypt':
/home/cee/Desktop/vanitygen-plusplus/util.c:681: undefined reference to `EVP_CIPHER_get_block_size'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:682: undefined reference to `EVP_CIPHER_get_block_size'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:682: undefined reference to `EVP_CIPHER_get_block_size'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:708: undefined reference to `EVP_CIPHER_get_key_length'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:708: undefined reference to `EVP_CIPHER_get_iv_length'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:713: undefined reference to `EVP_CIPHER_get_key_length'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:674: undefined reference to `EVP_CIPHER_get_block_size'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:675: undefined reference to `EVP_CIPHER_get_block_size'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:675: undefined reference to `EVP_CIPHER_get_block_size'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:749: undefined reference to `EVP_CIPHER_get_key_length'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/util.c:749: undefined reference to `EVP_CIPHER_get_iv_length'
/usr/bin/ld: simplevanitygen.o: in function `thread_loop_simplevanitygen':
/home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:130: undefined reference to `OSSL_PARAM_construct_utf8_string'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:131: undefined reference to `OSSL_PARAM_construct_end'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:132: undefined reference to `EVP_PKEY_CTX_set_params'
/usr/bin/ld: simplevanitygen.o: in function `get_public_key':
/home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:82: undefined reference to `EVP_PKEY_get_octet_string_param'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:84: undefined reference to `EVP_PKEY_get_octet_string_param'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:82: undefined reference to `EVP_PKEY_get_octet_string_param'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:84: undefined reference to `EVP_PKEY_get_octet_string_param'
/usr/bin/ld: /home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:82: undefined reference to `EVP_PKEY_get_octet_string_param'
/usr/bin/ld: simplevanitygen.o:/home/cee/Desktop/vanitygen-plusplus/simplevanitygen.c:84: more undefined references to `EVP_PKEY_get_octet_string_param' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:40: vanitygen++] Error 1
`

**Comment by 10gic** [comment]
What is the OpenSSL version in your system? 3.0.0 is the minimum supported version.

You can use `openssl version` to check the version, for example:
```
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

**Comment by ceemoneyx** [comment]
Thanks for the reply, I am indeed using 3.0.

For context: I’ve compiled vanitygen on the same device a few months ago
and that version still runs (however I don’t think OpenSSL 3 was installed
at that time because it won’t generate taproot addresses - says “OpenSSL
3.0 is required”)

Nix-build doesn’t seem to be compatible with Raspbian OS either

I’ve installed version 3 of OpenSSL and it didn’t fix that ISSUE so I’m
assuming I need to recompile vanitygen now that OpenSSL 3 is installed (as
you can tell I’m not an expert in this area)

Thanks again for you time and help
- Cee



So I’m trying to recompile it now that

**Comment by ceemoneyx** [comment]
So all that to say, yes I do indeed have OpenSSL 3.0 installed and am still getting that error

**Comment by 10gic** [comment]
I suspect that you have both an old version of openssl and a newer version of openssl in your system, and it is looking for the old version of openssl when compiling. You can specify to use the new openssl by modifying the Makefile.

**Comment by ceemoneyx** [comment]
Could I trouble you to show me how to modify the makefile? I know how to
open it/edit it but I’m not sure how to specify which OpenSSL version to
use

**Comment by 10gic** [comment]
Modify LIBS and CFLAGS to the new OpenSSL related directory, for example:
```
LIBS+=-L/usr/local/opt/openssl/lib
CFLAGS+=-I/usr/local/opt/openssl/include
```
