### ISSUE TITLE
When trying to import TRX Privkey into tronlink, it says Unrecognized key format

### ISSUE THREAD

**Issue by Bitcoin228** [10gic/vanitygen-plusplus#75]
D:\vanitygen-plusplus-master>vanitygen++ -C TRX TH
Generating TRX Address
Difficulty: 23
TRX Pattern: TH
TRX Address: THHC5PwGnHDFNC34wUuEtLgVztgcKvizBF
TRX Privkey: 1MmbZJRoHKX75mC2neUGimxvsZyZpf6KBxoNDVxogH3kevW424

D:\vanitygen-plusplus-master>vanitygen++ -C TRX TH
Generating TRX Address
Difficulty: 23
TRX Pattern: TH
TRX Address: THWHKaCA2PKwE1WvaDsryQMKFmEPXAYciq
TRX Privkey: 12Xex9nqXNSg8paLCFswi2V369NYxpLUPpN487G4NMA69EBiJGr

D:\vanitygen-plusplus-master>vanitygen++ -C TRX TH
Generating TRX Address
Difficulty: 23
TRX Pattern: TH
TRX Address: THKncSTLF7vJKFTpkXCTQ3nHqA6fym4TuV
TRX Privkey: 1Xv3jam8PX7zTSuwZebKAXhufrsSri3HvCzanuo3utoND7ekv2

D:\vanitygen-plusplus-master>

**Comment by 10gic** [comment]
@Bitcoin228 You are using the old version, please update the code to use the new version.

```
$ ./vanitygen++ -C TRX TH
Generating TRX Address
Difficulty: 23
TRX Pattern: TH
TRX Address: THZLn6ZF6rZ4Kct3PueN5vUMWRSFn61cDN
TRX Privkey: A97BBE02124B5372DFCE9ABE42F8F3AB64786418C0419878C8409C9F88D53238
```

**Comment by 10gic** [comment]
Note that TRX privkey in new version only contains hexadecimal strings.

**Comment by Bitcoin228** [comment]
Downloaded and installed the latest repository files
Didn't find problem

> @Bitcoin228Вы используете старую версию, обновите код, чтобы использовать новую версию.
> 
> ```
> $ ./vanitygen++ -C TRX TH
> Generating TRX Address
> Difficulty: 23
> TRX Pattern: TH
> TRX Address: THZLn6ZF6rZ4Kct3PueN5vUMWRSFn61cDN
> TRX Privkey: A97BBE02124B5372DFCE9ABE42F8F3AB64786418C0419878C8409C9F88D53238
> ```Downloaded and installed the latest repository files
Didn't find problem
