### ISSUE TITLE
release for windows

### ISSUE THREAD

**Issue by Bitcoin228** [10gic/vanitygen-plusplus#76]
Could you update the release https://github.com/10gic/vanitygen-plusplus/releases/tag/v0.1.0
vanitygen++ (preview) works well and needs to be updated under Windows. I can't build release for windows

**Comment by Bitcoin228** [comment]
Severity Code Description Project File String Suppression status
Error C1083 Cannot open include file: openssl/ec.h: No such file or directory, vanitygen D:\vanitygen-plusplus-master\simplevanitygen.c 1

**Comment by Bitcoin228** [comment]
Assembly started...
1>------ Build Started: Project: vanitygen, Configuration: Dynamic-Release x64 ------
1>stdafx.cpp
1>base32.c
1>D:\vanitygen-plusplus-master\base32.c(188,62): warning C4267: argument: conversion from "size_t" to "int"; possible data loss
1>crc16.c
1>ed25519.c
1>D:\vanitygen-plusplus-master\ed25519.c(1,10): fatal error C1083: Cannot open file include: openssl/ec.h: No such file or directory,
1>groestl.c
1>pattern.c
1>D:\vanitygen-plusplus-master\pattern.c(24,10): fatal error C1083: Cannot open include file: pthread.h: No such file or directory,
1>segwit_addr.c
1>sha3.c
1>simplevanitygen.c
1>D:\vanitygen-plusplus-master\simplevanitygen.c(1,10): fatal error C1083: Cannot open file include: openssl/ec.h: No such file or directory,
1>stellar.c
1>util.c
1>D:\vanitygen-plusplus-master\util.c(30,10): fatal error C1083: Cannot open file include: openssl/bn.h: No such file or directory,
1>vanitygen.c
1>D:\vanitygen-plusplus-master\vanitygen.c(24,10): fatal error C1083: Cannot open include file: pthread.h: No such file or directory,
1>winglue.c
1>D:\vanitygen-plusplus-master\winglue.c(21,10): fatal error C1083: Cannot open include file: pthread.h: No such file or directory,
1>Building project "vanitygen.vcxproj" failed.
========== Build: Successful: 0, Errors: 1, No Changes: 0, Skipped: 0 ==========

**Comment by luyuanshao** [comment]
really need it 💕💕.

**Comment by luyuanshao** [comment]
Hi @10gic 
I have encountered the same problem. Can you help us release a new version of Windows？

**Comment by 10gic** [comment]
@Bitcoin228 @luyuanshao There is a new release, see https://github.com/10gic/vanitygen-plusplus/releases/tag/v0.2.0
