### ISSUE TITLE
Windows Build. Cannot open include file: 'openssl/sha.h': No such file or directory

### ISSUE THREAD

**Issue by johngalt13** [10gic/vanitygen-plusplus#8]
I've installed everything. Trying to add #include path manually. And have no idea what to do. Can you make .sln for visual studio 2017/2019 or something? 
OpenSSL Dir added. Maybe too old version. 
Thank you very much

**Comment by NetherStar64** [comment]
I could fix that error with installing libssl-dev, but Building still doesn't work for me, I get ``` make -f Makefile.Win32
make: *** No rule to make target 'vanitygen.obj', needed by 'vanitygen.exe'.  Stop.```

**Comment by 10gic** [comment]
@johngalt13 Fix some build issues recently, it can be build by run `nmake -f Makefile.Win32`.
