### ISSUE TITLE
Initial vectors vulnability

### ISSUE THREAD

**Issue by CashCode** [10gic/vanitygen-plusplus#88]
Hello, Sirs.
Does the generation algorythm use initial vectors?
Is the code protected from vulnability of initial vectors, is it safe to use?

https://blog.1inch.io/a-vulnerability-disclosed-in-profanity-an-ethereum-vanity-address-tool/

**Comment by 10gic** [comment]
Vanitygen-plusplus uses openssl function EC_KEY_generate_key. See https://github.com/10gic/vanitygen-plusplus/blob/e0607a720de181c233db1c3ea97ca26ac9f1f3a7/oclengine.c#L2126
