### ISSUE TITLE
Windows 10 already compiled binaries?

### ISSUE THREAD

**Issue by NewCoNam** [10gic/vanitygen-plusplus#9]
Is there any already compiled windows .exe binaries available?

**Comment by 10gic** [comment]
I don’t have a Windows computer. 😞

**Comment by NewCoNam** [comment]
No, the blame is me. I should have already acquired a Linux system and
maybe it's high time I do. But think about adding ranges in your vanitygen
plus-plus. It increases entropy example:

Generate i.e. --r FFFFFFFF:000000000001  to create only vanitygen addresses
within that range.

Looking forward to your work

Regards

**Comment by 10gic** [comment]
Currently, private key prefix is supported.

If you want to generate vanity address from a range of private key, you can use `-Z` . For example, if you want to specify private key range:
```
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000FFFFFFFF
```
You can use the prefix:

```
00000000000000000000000000000000000000000000000000000000
```

Here is an example:
```
./vanitygen++ -v -Z 00000000000000000000000000000000000000000000000000000000 1111
Prefix difficulty:             16777216 1111
Difficulty: 16777216
Using 8 worker thread(s)
Pattern: 1111
Pubkey (hex): 04c9c9bcd9ed024ad273fe10c46378f57b340a9a42fac910d85a0cfcb451ec831ba085f7994afdeab9a94806cda8ad387c723daa54215f4cf7d7887d073bcd4665
Privkey (hex): 27F236AB
Privkey (ASN1): 307402010104200000000000000000000000000000000000000000000000000000000027f236aba00706052b8104000aa14403420004c9c9bcd9ed024ad273fe10c46378f57b340a9a42fac910d85a0cfcb451ec831ba085f7994afdeab9a94806cda8ad387c723daa54215f4cf7d7887d073bcd4665
Address: 1111LQtyBtNnEs4sYkCrYu3kmsLob2ui
Privkey: 5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kMZPFDikWRD2
```

**Comment by NewCoNam** [comment]
Thanks, I noticed that. Vanitygen plus-plus search starts at a specific
private key but does not specify an end key range. Also, a 'Count by' or
'stride'  feature would be good to maximize the speed of the GPU

Let me run some test, will let you know thanks

**Comment by NewCoNam** [comment]
Okay, managed to get it to work in Ubuntu for Windows needs many changes, I
may have a plan. Nothing is impossible, will reach out to you. Just be open
to my ideas.

Regards

**Comment by NewCoNam** [comment]
So, far an excellent variation to the vanitygen family of programs. You
really put a lot of work in it and your effort should be commented. Few
issues -k continue searching option only finds or repeats the same address
of a prefix it found.
example:
42f3a49eb6e08136a27dd50812aac230 -l $((256-20)) 16ctK
Difficulty: 4476342
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKjKbPJeY63RkN13Nqrv8M5ni9h4wek,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubxFt6crvDiU
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKjKbPJeY63RkN13Nqrv8M5ni9h4wek,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubxFt6crvDiU
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKky6Ruj2kMswsQ3zW95zQ7UfGC7KsD,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubtvbYZheW5E
BTC,16ctK,16ctKjKbPJeY63RkN13Nqrv8M5ni9h4wek,5HyyMTUkwPLz1h2ZCBDMLdNAdDDyYo1chCNRk3fubxFt6crvDiU
[560.13 Kkey/s][total 27121168][Prob 12.8%][50% in 4.4s][Found 16]

 Isn't it supposed to keep searching for the same pattern and produce all
addresses of the same pattern till I stop it?

Secondly, oclvanitygen++ displays this error when I run it:

Difficulty: 259627881
clGetPlatformIDs(0): Unknown code -1001
Could not open any device
clGetPlatformIDs(0): Unknown code -1001
Available OpenCL platforms:

Just few issues, still testing it

Regards

**Comment by 10gic** [comment]
1. This tool is not for brute-force search. There are some random mechanism in code. For more information, suggest you check https://github.com/10gic/vanitygen-plusplus/issues/7

2. Issue: clGetPlatformIDs(0): Unknown code -1001. What's the OS and GPU device you are using? PS: I only test oclvanitygen++ in CentOS with Nvidia GPU.

**Comment by NewCoNam** [comment]
Hi

Had the privilege of experimenting with your version of vanitygen plus and
its a great precision tool for finding vanitygen address. More importantly,
to get a greater understanding of keyspace distribution on the blockchain,
results are impressive.

I would like to know, if I want your vanitygen to load a file of prefixes
but only read first line of the file. How would I do that, which line
should I change?

Regards

**Comment by dextronomous** [comment]
Hi there, still great tool u built, but i cannot make it work, private key zero all the way down,
and was wondering could you maybe make a cuda windows build, supporting cuda i mean. thanks a lot sir.

**Comment by 10gic** [comment]
@dextronomous  Could you firstly confirm the cuda driver works in you windows? If so, post a screenshot about oclvanitygen++.exe failure.

**Comment by 10gic** [comment]
For the Windows 10 already compiled binaries, please refer to release.

**Comment by NewCoNam** [comment]
This pre-release
https://github.com/10gic/vanitygen-plusplus/releases/download/v0.1.0/prebuilt.win32.v0.1.0.zip
the oclvanitygen++ is crashing, vanitygen++ is working fine

**Comment by NewCoNam** [comment]
This is the complete error that I get:
Prefix difficulty:             16777216 1111
Difficulty: 16777216
Device: Intel(R) HD Graphics 520
Vendor: Intel(R) Corporation (8086)
Driver: 27.20.100.9316
Profile: FULL_PROFILE
Version: OpenCL 3.0 NEO
Max compute units: 24
Max workgroup size: 256
Global memory: 1672228864
Max allocation: 836114432
OpenCL compiler flags: -DDEEP_PREPROC_UNROLL -DCOMPRESSED_ADDRESS
Compiling kernel, can take minutes...done!
Build log:
1:1507:9: warning: 'hash_ec_point_inner_3' macro redefined
#define hash_ec_point_inner_3(i)                \
        ^
1:1388:9: note: previous definition is here
#define hash_ec_point_inner_3(i)                \
        ^
1:1522:9: warning: 'hash_ec_point_inner_5' macro redefined
#define hash_ec_point_inner_5(i)                        \
        ^
1:1406:11: note: previous definition is here
                #define hash_ec_point_inner_5(i)                        \
                        ^
1:1526:14: warning: incompatible pointer types passing 'uint [16]' to
parameter of type 'uchar *' (aka 'unsigned char *')
    sha3_256(hash2, hash1, 64);
             ^~~~~
1:1120:23: note: passing argument to parameter 'out' here
void sha3_256(uchar * out, const uchar * in, size_t inlen)
                      ^
1:1526:21: warning: incompatible pointer types passing 'uint [16]' to
parameter of type 'const uchar *' (aka 'const unsigned char *')
    sha3_256(hash2, hash1, 64);
                    ^~~~~
1:1120:42: note: passing argument to parameter 'in' here
void sha3_256(uchar * out, const uchar * in, size_t inlen)
                                         ^
1:1564:12: warning: incompatible pointer types passing 'uint [16]' to
parameter of type 'uchar *' (aka 'unsigned char *')
                sha3_256(hash2, ethrlp_buf, 23);
                         ^~~~~
1:1120:23: note: passing argument to parameter 'out' here
void sha3_256(uchar * out, const uchar * in, size_t inlen)
                      ^
Grid size: 3072x2048
Modular inverse: 6144 threads, 1024 ops each
Available OpenCL platforms:
0: [Intel(R) Corporation] Intel(R) OpenCL HD Graphics
  0: [Intel(R) Corporation] Intel(R) HD Graphics 520, endian little: true
1: [Intel(R) Corporation] Intel(R) OpenCL
  0: [Intel(R) Corporation] Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz,
endian little: true
Using OpenCL prefix matcher

**Comment by 10gic** [comment]
Some guy (See https://github.com/10gic/vanitygen-plusplus/issues/12) run it in windows successfully with latest code. Suggest build it by yourself, try again.

**Comment by NewCoNam** [comment]
Tried building myself with a host of errors, maybe that user can share his
build as a windows release? Maybe he got something right that I am missing

**Comment by 10gic** [comment]
@NewCoNam What error did you encounter? Share the output of command `nmake /F Makefile.Win32`.

**Comment by NewCoNam** [comment]
Hi, After months of trying to get vanitygen plus plus to work on various
gpu drives I am still struggling vanitygen++ works well, but only does 2,1
m/keys per second. It would be very good to get it to work on windows gpu
like my ryzen amd 7.

Regards
