### ISSUE TITLE
Feature request: Support multiple GPUs (parallel GPU computation)

### ISSUE THREAD

**Issue by ottok** [10gic/vanitygen-plusplus#95]
This is a very cool tool, thanks for creating it!

While running it I noticed it only uses a single CPU. It would be cool if it supported running on multiple GPUs in parallel.

![image](https://github.com/10gic/vanitygen-plusplus/assets/668724/f5945932-34de-4468-9a18-ccb8e410722e)

**Comment by ottok** [comment]
I just tested https://github.com/1inch/profanity2 and it seems to run on all available GPUs by default. Perhaps you can take a peek at their implementation as reference.

![image](https://github.com/10gic/vanitygen-plusplus/assets/668724/29eec8e2-b788-442e-85ba-d8117f201342)

**Comment by 10gic** [comment]
In multi-GPU scenarios, please specify the `-D` parameter.

**Comment by ottok** [comment]
> In multi-GPU scenarios, please specify the `-D` parameter.

I did and I can use it to select which GPU device to use (e.g. `-D 0` or `-D 1`) but I did not find any way to tell it to use more than one GPU. Can you please share what syntax can achieve that?

**Comment by 10gic** [comment]
Usage:
```
$ ./oclvanitygen++
......
-D <devstr>   Use OpenCL device, identified by device string
              Form: <platform>:<devicenumber>[,<options>]
              Example: 0:0,grid=1024x1024
......
```

**Comment by 10gic** [comment]
`-D` parameter comes from the original vanitygen project. I don’t have a multi-GPU device at hand. Try specifying the `-D` parameter multiple times.

**Comment by ottok** [comment]
> `-D` parameter comes from the original vanitygen project. I don’t have a multi-GPU device at hand. Try specifying the `-D` parameter multiple times.

I tried. It will only use one device in all scenarios I tested, and if I do `-D 0 -D 1` it picks ends up running only on device '1'.

**Comment by 10gic** [comment]
Usage:
```
-D <devstr>   Use OpenCL device, identified by device string
              Form: <platform>:<devicenumber>[,<options>]
              Example: 0:0,grid=1024x1024
```

For example, try `./oclvanitygen++ -v -D 0:0 -D 0:1 -D 0:2 1ove`
